# workspace (GOPATH) configured at /go
FROM golang:1.19 as builder

WORKDIR /app

ADD . /app

# Copy the local package files to the container's workspace.
COPY . ./

# installing depends and build
RUN make build-linux

FROM alpine:latest

COPY --from=builder app/bin/evrone_api_gateway ./evrone_api_gateway

RUN chmod +x ./evrone_api_gateway

CMD ["./evrone_api_gateway"]
